### ISSUE TITLE
Remove debugging print to STDOUT

### ISSUE THREAD

**Issue by TheKrafter** [ItsShamed/MCCTDW#4]
The plugin sends the json it's going to send to discord to STDOUT. This was probably done for debugging, and should be removed as it clutters up the server console. Below is the server console output:

<details>

```
[20:26:05 INFO]: TheKrafter2217 lost connection: Disconnected
[20:26:05 INFO]: [MCCTDW] [STDOUT] {
  "tts": false,
  "embeds": [
    {
      "color": 16733525,
      "author": {
        "name": "TheKrafter2217 left the game.",
        "icon_url": "https://minotar.net/helm/3b27ca8c-9f8e-4254-a7c3-a1031f085456/100.png"
      }
    }
  ]
}
[20:26:05 WARN]: Nag author(s): '[ItsShamed]' of 'MinecraftChatToDiscordWebhook' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
```

</details>

**Comment by TheKrafter** [comment]
Running the latest version from [releases](https://github.com/ItsShamed/MCCTDW/releases).
It looks like this [was solved](https://github.com/ItsShamed/MCCTDW/commit/b92a3bfa0ddf7b9b2a9370389e4b48dfc0f6cd87) but a new release has not been built.
Could you build an updated release?

**Comment by TheKrafter** [comment]
Otherwise this plugin is great btw, nice and quick setup for a small thing I dont wanna set up another DiscordSRV bot for

**Comment by ItsShamed** [comment]
https://github.com/ItsShamed/MCCTDW/releases/tag/MCCTDW-1.1
